#include "catalogue.h"

Article Catalogue[CATALOGUE_SIZE] = {
    {
        "00000",
        "Colgate",
        "Dentifrice",
        CAT_Hygiene,
        SBCAT_Toothpaste,
        "Colgate",
        "",
        "NA",
        {0, 0, 0},
        0.0,
        1000,
        50
    },
    {
        "00001",
        "Adidas",
        "Chaussure",
        CAT_Clothes,
        SBCAT_Shoe,
        "Adidas",
        ""
        "",
        {0, 0, 0},
        0.0,
        1000,
        50
    },
    {
        "00002",
        "Bic",
        "Stylos",
        CAT_Stationery,
        SBCAT_Pen,
        "Bic",
        "",
        "NA",
        {0, 0, 0},
        0.0,
        1000,
        50
    },
    {
        "00003",
        "Charral",
        "Beuf",
        CAT_Food,
        SBCAT_Meat,
        "Charral",
        "",
        "NA",
        {0, 0, 0},
        0.0,
        1000,
        50
    },
    {
        "00004",
        "Monoprix",
        "Carottes",
        CAT_Food,
        SBCAT_Vegetables,
        "Monoprix",
        "",
        "NA",
        {0, 0, 0},
        0.0,
        1000,
        50
    },
    {
        "00005",
        "Harry Potter And the Chamber of Secrets",
        "Livre",
        CAT_Culture,
        SBCAT_Book,
        "Hachette",
        "",
        "NA",
        {0, 0, 0},
        0.0,
        1000,
        50
    },
    {
        "00006",
        "Acer",
        "Ordinateur",
        CAT_Computers,
        SBCAT_Computers,
        "Acer",
        "",
        "NA",
        {0, 0, 0},
        0.0,
        1000,
        50
    },
    {
        "00007",
        "Displate",
        "Poster",
        CAT_Decoration,
        SBCAT_Poster,
        "Displate",
        "",
        "NA",
        {0, 0, 0},
        0.0,
        1000,
        50
    },
    {
        "00008",
        "Razer",
        "Clavier",
        CAT_Computers,
        SBCAT_Keyboard,
        "Razer",
        "",
        "NA",
        {0, 0, 0},
        0.0,
        1000,
        50
    },
    {
        "00009",
        "Supreme",
        "T Shirt",
        CAT_Clothes,
        SBCAT_Shirt,
        "Supreme",
        "",
        "NA",
        {0, 0, 0},
        0.0,
        1000,
        50
    }
};